### ISSUE TITLE
Cannot serialize Kotlin type (after update from 1.8.0 -> 1.9.1)

### ISSUE THREAD

**Issue by doniwinata0309** [square/moshi#1001]
Hi, I have a simple class to add default value on json response if field = null.
I have unit test for this, it was working on 1.8.0, but I got error after updating to 1.9.1.

Please find my attachment to repro the issue:
[moshi.zip](https://github.com/square/moshi/files/3803042/moshi.zip)

This is the stacktrace of the failed test.
https://scans.gradle.com/s/2bvpmnh4lnujk/tests/qpp7gaov2u6ps-pejo3vvrv55m6

Then i tried to add   `@JsonClass(generateAdapter = true)` on my Response class, the error become:
https://scans.gradle.com/s/ehyipl5s7qguo/tests/qpp7gaov2u6ps-pejo3vvrv55m6?openStackTraces=WzFd

So it seems the generated not found because this class is created on test folder. So i moved Response.kt from test to main folder:
The previous tests was successful now, but it breaks another test:
https://scans.gradle.com/s/3ggowvco5c652/tests/qpp7gaov2u6ps-r36aurfmjhh3w?openStackTraces=WzBd

Is it expected behaviour or there is a bug ? Let me know if you need additional information, Thanks !

**Comment by ZacSweers** [comment]
> This is the stacktrace of the failed test.

This is explained the changelog for 1.9.0, first item: https://github.com/square/moshi/blob/master/CHANGELOG.md#version-190

> So it seems the generated not found because this class is created on test folder. So i moved Response.kt from test to main folder:

This is because you need to add `testKapt(...)` for the moshi code gen to run on test sources. It worked when you moved it to main sources because you were using `kapt(...)` already

> The previous tests was successful now, but it breaks another test:

This test failure appears to be legit. That line in your project is passing in an empty json blob but the `booleanValue` property is required. Since it's missing from the json, the exception is thrown back to you. It may have passed before with reflection on 1.8.0 because it was using java reflection, but in fact this is the exact kind of reason Moshi now prohibits that: java reflection was willfully forcing a `null` value into a non-nullable property. This would have failed at runtime with a confusing NPE.
