### ISSUE TITLE
Suppress deprecation warnings if any properties or target classes are deprecated

### ISSUE THREAD

**Issue by ZacSweers** [square/moshi#1023]
This prevents using `warningsAsError` or `-Werror` in compilations otherwise

Thanks to @erichkleung for the report

**Comment by swankjesse** [comment]
I really don’t like how `-Werror` interacts with deprecation warnings. There’s a tracking bug for this here: https://youtrack.jetbrains.com/issue/KT-24746

**Comment by ZacSweers** [comment]
Agreed, but this at least ensures moshi doesn't become a snag on some codebases for that. Alternatively, we could just stick a blanket "suppress all" defensively on all classes?

**Comment by ZacSweers** [comment]
FWIW, Dagger appears to suppress defensively too. All its generated factories have this

```java
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
```

**Comment by ZacSweers** [comment]
Bad news - I think this exposed a bug in kapt. Stubs don't include deprecated annotations (from either Java or Kotlin), so the processor can't check if a class or property is deprecated. Filed https://youtrack.jetbrains.com/issue/KT-34951

**Comment by ZacSweers** [comment]
PR for a blanket defensive suppression for now - #1028

**Comment by ZacSweers** [comment]
Deprecations readability will be fixed in Kotlin 1.3.70 https://youtrack.jetbrains.com/issue/KT-30368

**Comment by bendaniel10** [comment]
I am having an issue that is related to this. 

The difference is that the generated adapter source code is importing a java class that is deprecated. Unfortunately the class level `@Suppress("DEPRECATION")` does not extend to the imports section. 

It might be better if the suppress annotation is moved to the file level, `@file:Suppress("DEPRECATION")`, so that it covers the imports section as well.
