### ISSUE TITLE
Info: @Json annotation and complex path

### ISSUE THREAD

**Issue by artecoop** [square/moshi#1051]
Hello everyone!

I'm here to ask if there is the possiblity to map via `@Json` annotation a complex path.
For example imagine this json
```
{
    "foo": {
        "bar": {
            "value: "mickey mouse"
        }
    }
}
```

In order to serialize this json in a poko (or pojo, you pick) I need to create a class for foo and a class for bar, the last one containing the "value" field.

Is it possible to map the '@Json' annotation like this: `@Json(name = 'foo.bar.value')` or `@Json(name = 'foo/bar/value')` to skip some cluttering classes and go straight to the string?

Thanks in advance!

**Comment by JakeWharton** [comment]
You'll need to write a custom adapter for this. There's so many things to consider here that makes it unsuitable for a library feature. For example, what happens to sibling keys in "bar" or "foo"? Are they discarded? Can they still be bound? What happens if someone binds a property twice using both JSON path notation and traditional object binding?

These are questions that don't have easy answers which makes it better for an opinionated sibling library rather than in the core of Moshi.
