### ISSUE TITLE
Kotlin Pair / Triple Type Adapters

### ISSUE THREAD

**Issue by james-novino** [square/moshi#1078]
Currently, the `Pair` and `Triple` objects in Kotlin do not serialize by default and require custom type adapters to be registered. Both`Pair` and `Triple` are core language constructs and are widely used within Kotlin projects. 

There are some questions about what shape Pair/Triples should take:
```
["a", "b"]
```
or like a data class:
```
{
  "first": "a",
  "second": "b"
}
```
GSON  and other serializers treat this Pairs, Tuples as a JSON Object and I think it's a safe change to assume for the default handling. 

It would be helpful to include these adapters by default in Moshi.

**Comment by JakeWharton** [comment]
To be clear, Gson is wrong here because it serializes the implementation of a type that you do not control. Kotlin would be well within its rights to rename the fields which back the `first` and `second` properties and break everyone who is erroneously relying on Gson's behavior.

I don't think we should do anything by default here. It's trivial to write a `@FromJson` or `@ToJson` for these types allowing you to choose which representation, if any, you want.

The worst thing we could do is serialize an object whose type uses `Pair` or `Triple` deep in its type hierarchy without requiring the user to explicitly define _how_ that should appear in the serialized form.

**Comment by ZacSweers** [comment]
Agreed, we have avoided a lot of gson's footguns by not trying to automagically support platform types beyond primitives/collections/string/enum.

**Comment by james-novino** [comment]
While I understand the reasoning behind not trying to replicate the `footguns` of GSON. However, if the Kotlin language were to change the values or APIs for Pair from `first` and `second` serialization wouldn't be the only thing that would break. It would fail to compile in most applications.

**Comment by JakeWharton** [comment]
We're talking about the private fields which back the public properties, not the properties themselves. Gson doesn't care about Kotlin property names, only the private field names. So that's not actually true.
