### ISSUE TITLE
Moshi Cannot Serialize Throwable or Kotlin Exception

### ISSUE THREAD

**Issue by james-novino** [square/moshi#1079]
There are no default handlers for `Throwable` despite Throwable, there are also no samples showing the best practices for writing an adapter to serialize exceptions. 

Code to reproduce: 
```kotlin
var moshi = Moshi.Builder().build()
val adapter = moshi.adapter<Any>(Object::class.java)

val exception = Exception("Hello")
val json = adapter.toJson(exception)
println(json)
```
I understand the argument for keeping Moshi as un-opinionated as possible but I think certain core types deserve at least a sample of how to handle them.

**Comment by ZacSweers** [comment]
Would argue there's no best practice we could recommend for those types. They're not intended for json serialization, and trying to make recommendations would be a fruitless pursuit as everyone uses exceptions in different ways. I would suggest modeling error types as a plain value type rather than trying to make them inherit from exception or throwable. Doing so is usually a sign that you really just want it to be a shortcut to `throw` a decoded model.

**Comment by james-novino** [comment]
In general exceptions or throwables are just data classes that can be serialized as JSON. It's a pretty common use case for most applications to want to be able to return exception information, especially for internal applications. Without the ability to serialize java exceptions natively leaves most consumers to have to implement reflection-based serializer for those classes. 

Is there something, in particular, you're aware of with Java exceptions that would violate JSON best practices?

**Comment by jcholin** [comment]
@james-novino did you managed to handle this case? I have the same issue and wonder how to solve it
