### ISSUE TITLE
Filter unrecognized Enum out of a List of Enum

### ISSUE THREAD

**Issue by rewgoes** [square/moshi#1118]
Consider the following use case:
The API returns a `List<Enum>` which is used to know which features are available to the user. As new features are added to the service, new `Enum` values are added/returned by the API.

In this case, users running old versions of the app won't have the new values related to the new features. So, as the app needs a list of only the values that it recognizes, it would be ideal if Moshi could filter the unrecognized `Enum` values from the `List`.

As I workaround, I've developed the following adapter for now:

```kotlin
class SkipBadEnumListAdapter(private val elementAdapter: JsonAdapter<Enum<*>>)
    : JsonAdapter<List<Enum<*>>>() {
    object Factory : JsonAdapter.Factory {
        override fun create(type: Type, annotations: MutableSet<out Annotation>, moshi: Moshi)
                : JsonAdapter<*>? {
            return if (annotations.isEmpty()
                    && Types.getRawType(type) == List::class.java
                    && type is ParameterizedType
                    && type.actualTypeArguments.size == 1
                    && Types.getRawType(type.actualTypeArguments[0]).isEnum) {
                val elementType = Types.collectionElementType(type, List::class.java)
                val elementAdapter = moshi.adapter<Enum<*>>(elementType)
                SkipBadEnumListAdapter(elementAdapter).nullSafe()
            } else {
                null
            }
        }
    }

    override fun fromJson(reader: JsonReader): List<Enum<*>>? {
        val result = mutableListOf<Enum<*>>()
        reader.beginArray()
        while (reader.hasNext()) {
            try {
                val peeked = reader.peekJson()
                elementAdapter.fromJson(peeked)?.let { result.add(it) }
            } catch (ignored: JsonDataException) {
                // Skip bad element ;)
            }
            reader.skipValue()
        }
        reader.endArray()
        return result

    }

    override fun toJson(writer: JsonWriter, value: List<Enum<*>>?) {
        if (value == null) {
            throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
        }
        writer.beginArray()
        for (i in value.indices) {
            elementAdapter.toJson(writer, value[i])
        }
        writer.endArray()
    }
}
```

**Comment by rewgoes** [comment]
I've just found out that this is something that some people have already discussed or had some sort of implementation using Typed adapters:

- [StackOverflow - Moshi Custom Adapter for generic List<T:Enum>](https://stackoverflow.com/questions/53670232/moshi-custom-adapter-for-generic-listtenum-returns-listlisttenum-instead)
- [Some project in GitHub](https://github.com/DeveloperPaul123/MHWDatabase/blob/master/app/src/main/java/com/developerpaul123/mhwdatabase/adapters/SkipNotFoundEnumInEnumListAdapter.kt)

I just wonder if this could be the **default behavior** for Moshi, so instead of failing the request it just skips invalid values without adding any adapter.

The reason for this is:
- Performance: I don't think using an Adapter factory has a good performance
- Code maintenance: Using a Typed Adapter might solve the problem for an Enum type now, but in the future, other developers might call another type of Enum(`List<Enum>`) and they forget to create the Adapter for that.

Please, if you agree that Moshi should have this as default behavior or allow this to change through a builder configuration, I can start implementing the changes for that.

**Comment by rharter** [comment]
This won't become the default behavior since it means that Moshi will silently lose data.  A simple test for this is to deserialize a JSON string, then serialize it: the default behavior should result in serialized output that matches the input, anything else needs to be opt in.

That being said, check out the [EnumJsonAdapter](https://github.com/square/moshi/blob/master/adapters/src/main/java/com/squareup/moshi/adapters/EnumJsonAdapter.java) in the [moshi-adapters](https://github.com/square/moshi/tree/master/adapters) artifact. That allows you to specify a fallback value when the actual value is unknown.

Here's how I would use it in your case:

```kotlin
Moshi moshi = new Moshi.Builder()
    .add(
        Feature.class,
        EnumJsonAdapter.create(Feature.class).withUnknownFallback(Feature.Unknown)
    )
    .build();
```

That should allow you to avoid needing a custom adapter and get you the functionality you are looking for.

**Comment by rewgoes** [comment]
I agree that it may not be the default, but I also said to allow this to be set on the builder configuration, through some new flag, eg. `skipUnknownEnumInList`.

Using EnumJsonAdapter would affect the entire Enum, the problem only happens when using the Enum in a `List<Enum>`. In addition, as I said, all developers would need to be aware that they have to create a new EnumJsonAdapter whenever they use a different kind of Enum in a `List<Enum>`.

IMHO, if I set `skipUnknownEnumInList` on the builder, I would be happier that Moshi silently loses some unknown and useless Enum value in a List, than loudly fail the entire request and break the app in production.

**Comment by rharter** [comment]
This type of functionality is not the responsibility of Moshi as a whole, it's the responsibility of the adapter that handles lists of enums. Therefore adding a builder parameter for constructing your Moshi instance isn't the right place for this.  Adding an adapter to the builder is the correct approach, in the same way you add adapters to deal with other types in custom ways.

As for the unknown value handling, Moshi has built in functionality for enums that requires values from the JSON to match possible enum values (one of Moshi's principals is not silently losing data).  If you'd like support for unknown values in enums, you can use the `EnumJsonAdapter` linked above. This makes allowing unknown types an explicit opt-in per enum, as otherwise could be a very dangerous situation.

If you want to skip the unknown values of your enum, then you could either write your own adapter (as you've done), or simply filter the result, i.e. `moshi.fromJson<List<MyEnum>>(json)?.filter { it != MyEnum.Unknown }`. 

At its core Moshi doesn't know how to handle "lists of enums" any differently than any other list. It uses a composable approach that knows how to parse a list of things, and uses the registered adapter for the lists content type to parse the content.  This is important, otherwise users would have to register an adapter for every type, then another adapter for a list of every type.

This also means that types are handled the same by Moshi whether they're contained in a list or not, which your proposal violates.  The proposal suggests that enums in a list will drop unknown values, but those same enums as a property would throw a JsonDataException. That would be quite surprising for users who have no problem parsing a list of Feature enums but experience errors when they try to parse that same enum as a property of an object.

Overall, the approach you've defined above, creating a custom adapter to handle custom requirements, is the correct approach.  Moshi was designed to support custom use cases like this.

While others may have run into this issue as well, this is a specific requirement that doesn't align with many of the core values of Moshi, so it's unlikely to be included. As a general use library, Moshi has different requirements than individual apps, however, so if this adapter meets your needs then I encourage you to continue using it, and share it with others who have the same requirements.
