### ISSUE TITLE
Type erasure values of Map<String, Any> type

### ISSUE THREAD

**Issue by ArtemyGlukhov** [square/moshi#1144]
Good day. I am currently writing tests and I am observing strange behavior with what happens to the value types of the Map from JSON. 

Let's code, I have this test:
https://gist.github.com/ArtemyGlukhov/f7987eb5b42b5779208c18e05fbb5b4a

So, I'm put to the Map<String, Any> some values with different types, such Int, Long, Double
Then I get JSONObject from it, and json string looks like correct:
`{"d":{"any_string_key":"any_string_value","any_boolean_key":true,"any_int_key":100,"any_long_key":10000,"any_double_key":1000000.0},"provider":"provider_name","uid":"provider_uid"}` 

BUT,  when I get the result of execution of:
`val data : MutableMap<String, Any> = mapAdapter.fromJson(jsonObj.get("d").toString()) as MutableMap<String, Any>` as Map, then map's values types is only Double, but not Int or Long, as I expect. 

![Снимок экрана 2020-05-22 в 21 29 06](https://user-images.githubusercontent.com/44549681/82698420-66515600-9c73-11ea-8330-ca685c2d591b.png)

Please tell me, is this the expected behavior or bug?

**Comment by james-novino** [comment]
JSON doesn't have unique types for Int, Double, Long it only has a number type. When deserializing a JSON number to a Kotlin Any moshi uses the highest precision i.e Double to avoid truncating the value.

**Comment by ColtonIdle** [comment]
@ArtemyGlukhov oooh! I think if we get a solution to this, we could also resolve the issue surrounding the DefaultIfNullFactory 
 defined here: https://github.com/square/moshi/issues/843https://github.com/square/moshi/issues/843

**Comment by swankjesse** [comment]
We won’t be changing maps to use types other than doubles.

**Comment by ColtonIdle** [comment]
@swankjesse understood.

Do you think it's reasonable to ask on moshis issue tracker for specific help on implementing `DefaultIfNullFactory` that @ZacSweers provided here https://github.com/square/moshi/issues/843#issuecomment-584842727 ?

I only ask because the DefaultIfNullFactory works great for the vast number of cases, but I wrote 3 tests here and I show how 1 of the simple test cases fails https://github.com/square/moshi/issues/843#issuecomment-615363456

At this point, Jake and Zac have both said it's possible to have a DefaultIfNullFactory, and more and more users have asked about it but it still has issues, and I spent hours/days trying to figure out if I'm just stupid and doing something wrong, but I literally don't understand how it could be possible to write a DefaultIfNullFactory with this "type erasure" problem that's mentioned by the OP.

**Comment by ZacSweers** [comment]
Usage questions should go on stackoverflow

**Comment by ColtonIdle** [comment]
@ArtemyGlukhov the newest version of moshi has a new feature

>New: JsonReader.nextSource(). This returns an Okio BufferedSource that streams the UTF-8 bytes of a JSON value. Use this to accept JSON values without decoding them, to delegate to another JSON processor, or for streaming access to very large embedded values.

You might be able to use that to your advantage here?
