### ISSUE TITLE
[JsonReader] Unchecked exceptions thrown when parsing invalid json format

### ISSUE THREAD

**Issue by serhii-tiurenko** [square/moshi#1145]
Change type of the JsonDataException to not inherit RuntimeException. Unchecked exceptions by design is for critical errors from which there is no proper recovery logic possible and this is not the case for malformed json file. For example: if json is just an obsolete cache file, preference saved value that became invalid after application update.

We can either define some common parent class for Json exceptions thrown by Moshi or use IOException for backward compatibility. However, later approach doesn't sound like a valid abstraction for this.

**Comment by JakeWharton** [comment]
> Unchecked exceptions by design is for critical errors from which there is no proper recovery logic possible

I don't think this blanket statement holds and so I don't really buy the rest of the argument. If you call `Integer.parseInt("bob")` you get an unchecked `NumberFormatException`.

Even beyond the argument itself, this change, while binary compatible, is severely source-incompatible and would dramatically harm the usability and upgrade path of consumers.

**Comment by serhii-tiurenko** [comment]
Not sure what you want to tell with parseInt example. Use-cases for it are a lot simpler than json parsing and, as you probably know, for this method declaration:
   public static int parseInt(String s) throws NumberFormatException
The only reason it throws runtime exception is to not enforce try-catch block in java and it is not used that often to cause problems. And here is declaration we have: 
  public final @Nullable T fromJson(String string) throws IOException
Here we already enforcing try-catch block with IOException, so you are losing the only benefit from making it a runtime exception.

Source-compatibility is an issue thou. We can start at least with documenting this exception and later, when enough changes are gathered for 2.0 version, add this into the mix. Just consider this, by having it return IOException you are limiting your error reporting to subclasses of it, which can be confusing sometimes (not only to me according to the archive of issues here). Having your own exception class will give you flexibility to extend error reporting logic.

And the more this will be dragged on, the harder it will be to update later as I don't see Mochi popularity declining any time soon.

Thank you.

**Comment by swankjesse** [comment]
Our current design is correct. The alternatives are bad!

 * Extend `IOException`. This is terrible because it mixes programmer mistakes that you catch in testing (I used a string where I should have an object) with operational problems that you catch in production (the disk filled up, etc.).

 * Invent a new checked exception. This is terrible because it completely mindless work for the programmer. Programmers don’t expect schema mismatches to happen in practice, and having to write code to handle them is a waste of their very expensive time.

**Comment by swankjesse** [comment]
(what would the `catch` clause have looked like for your obsolete cache file, had you been forced to write one?)

**Comment by serhii-tiurenko** [comment]
try {
} catch (exc: JsonEncodingException) {
  removeObsoleteKey(key)
} catch (exc: JsonDataException) {
  removeObsoleteKey(key)
}

Question: From what point in time migrations issues stopped being something that should be handled? Databases do this, but sometimes your data structures are to simple to have database, what then?

**Comment by swankjesse** [comment]
This isn’t a good venue to debate the merits of checked vs. unchecked exceptions.

We have taken the stance that you we shouldn’t force all developers to recover from potential JSON type errors, because we believe such errors are rare in practice, and usually the best action is to crash.

If you do want to recover from them you have the option of catching a `JsonDataException`, just as you also have the option to catch `ConcurrentModificationException` when the need strikes.
