### ISSUE TITLE
Support Java record classes when they are stable

### ISSUE THREAD

**Issue by piorrro33** [square/moshi#1278]
As of the latest release `2.11.0` (and probably past releases too) Moshi is not able to deserialize Java Records, it simply fails with an `AssertionError` when calling `Adapter#fromJson` with an appropriate JSON object.
See the attached very simple sample project for more details: [test_project.zip](https://github.com/square/moshi/files/5630567/test_project.zip)
Stacktrace:
```
Exception in thread "main" java.lang.AssertionError
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:208)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:51)
	at Main.main(Main.java:8)
```

**Comment by ZacSweers** [comment]
Moshi may support records in the future once records are stable, but for now you can use this implementation: https://github.com/ZacSweers/MoshiX/tree/main/moshi-records-reflect

**Comment by ItsTehBrian** [comment]
Java 16 was released just recently and brought with it full support for records. Since they are now deemed stable enough to no longer be a preview feature, have there been any updates for this issue regarding serializing and deserializing them? It would be much more convenient to use records rather than writing out all the boilerplate (ie. getters, constructors) usually needed for a POJO. Apologies if this topic has already been discussed elsewhere, I don't keep up with Moshi's development very much. Thanks in advance 😄

**Comment by ZacSweers** [comment]
It's been stable for two days, give us some time :)

**Comment by erethir** [comment]
Hello! What is the status of this one?

**Comment by JakeWharton** [comment]
Open!

**Comment by TehBrian** [comment]
This is great! Thanks for all of your hard work :D
