### ISSUE TITLE
Using class delagation val keeps default value

### ISSUE THREAD

**Issue by mantas84** [square/moshi#1284]
I was trying to implement class delegation. Moshi keeps all val properties with default values, but works with vars. Why?
Short example:

```kotlin
data class Article(
    @Transient
    private val data: BaseEntityData = BaseEntityData(),
    var number: Int,
) : BaseEntity by data

interface BaseEntity {
    var titleVar: String?
    val titleVal: String?
}

@JsonClass(generateAdapter = true)
data class BaseEntityData(
    override var titleVar: String? = null,
    override val titleVal: String? = "But why?"
) : BaseEntity
```

```kotlin
class Sample {

    private val json = "{" +
            "\"number\":1," +
            "\"titleVar\":\"var\"," +
            "\"titleVal\":\"val\"" +
            "}"

    private val moshi = Moshi.Builder()
        .addLast(KotlinJsonAdapterFactory())
        .build()

    private val adapter = moshi.adapter(Article::class.java)

    @Test
    fun sample() {
        val article = adapter.fromJson(json)!!
        Assert.assertEquals(1, article.number)
        Assert.assertEquals("var", article.titleVar)
        Assert.assertEquals("val", article.titleVal)
    }

}
```

Output:
`expected:<val> but was:<But why?>`

**Comment by ZacSweers** [comment]
Moshi can only fulfill vals handled in the constructor.

In your constructor, data is transient but fulfills the entity properties. Moshi can fulfill the var property because it's settable after instantiation, but the val property is not and that's why you're just getting the delegated value that your default data instance.

I'd suggest looking at the generated adapter in the future as they're pretty readable and show the behavior there.

**Comment by mantas84** [comment]
In generated BaseEntityDataJsonAdapter both val var fields looks the same. 
Article uses reflection adapter. Shouldn't reflection adapter treat delegated var val same? (Codegen adapter is hardly readable to me)

Putting  @JsonClass(generateAdapter = true) on Article class would exclude transient data field from adapter. 

So basically now: 
codegen-> uses default values,
reflection-> uses default values for val, correct values for var.

**Comment by ZacSweers** [comment]
We might have a behavior parity issue with code gen there that we can fix, but to be totally clear moshi's kotlin reflection doesn't claim to set private/immutable properties. It's just that it uses kotlin-reflect to interact with kotlin APIs idiomatically rather than try to perceive them purely through java reflection

**Comment by ZacSweers** [comment]
Nothing more to do here. The failing "val" test is expected behavior, and Moshi isn't going to call a `var` setter that was already set in the constructor
