### ISSUE TITLE
Build fails with Kotlin codegen

### ISSUE THREAD

**Issue by abredykhin** [square/moshi#1338]
I'm using Android Studio 4.2 and Kotlin codegen build fails on nearly empty test project (attached). I enabled `kapt` plugin and have the following dependencies in the test project

```kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.4.32"
    implementation "com.squareup.retrofit2:converter-moshi:2.5.0"
    implementation "com.squareup.moshi:moshi:1.12.0"
    kapt "com.squareup.moshi:moshi-kotlin-codegen:1.8.0"
```

My test class definition: 

```kotlin
@JsonClass(generateAdapter = true)
data class MyClass(
    val name: String
)
```

I get this error when building: 
```
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)
```

Please advise if I'm doing something wrong or how I can resolve the build error. 

Thanks 

[MoshiTest.zip](https://github.com/square/moshi/files/6429750/MoshiTest.zip)

**Comment by ZacSweers** [comment]
Two things
- you're using a much older version of code gen than the rest of Moshi, we don't make any guarantees about running code gen with different versions of moshi's runtime.
- you're using a very old version of code gen, update to 1.12.0 and feel free to revisit if there is still an issue

In the future, it helps to paste the entire stacktrace as well rather than a partial snippet with no context
