### ISSUE TITLE
Can you add an option for KotlinJsonAdapterFactory to support platform class?

### ISSUE THREAD

**Issue by jiqimaogou** [square/moshi#1572]
some public platform classes like Pair and Triple I think can be jsoned.

**Comment by JakeWharton** [comment]
Are they serialized as an array or as an object with keys?

**Comment by jiqimaogou** [comment]
object with keys:
```
{
   "first": 1,
   "second":2
}
```

in ClassJsonAdapter.kt there is the code:
```
      if (rawType.isPlatformType) {
        type.throwIfIsCollectionClass(List::class.java)
        type.throwIfIsCollectionClass(Set::class.java)
        type.throwIfIsCollectionClass(Map::class.java)
        type.throwIfIsCollectionClass(Collection::class.java)

        val messagePrefix = buildString {
          append("Platform $rawType")
          if (type is ParameterizedType) {
            append(" in $type")
          }
        }
        throw IllegalArgumentException(
          "$messagePrefix requires explicit JsonAdapter to be registered"
        )
      }
```

Is it convenient to add an option to bypass this check?

**Comment by JakeWharton** [comment]
You can write your own serializer for these types.

The point of my question was that these types usually have ambiguities in how they should be serialized. Moreover, because they don't intrinsically map to something in the JSON spec (like a list does), it means you are relying on whatever choices we make and those are unlikely to be the ones which satisfy everyone. It's much easier to push these decisions to callers so that they understand and are in control of how types that neither they nor Moshi own are serialized.
