### ISSUE TITLE
@Json(name = "key") with KotlinJsonAdapterFactory not working when using kotlin 1.8.x and R8.

### ISSUE THREAD

**Issue by alifTC12** [square/moshi#1679]
We just upgrade our android kotlin version from 1.7.20 to 1.8.0 then suddenly some issue happened on our apps.
We could reproduce the issue by this snippet code: 

```
class MainActivity : AppCompatActivity() {

    @Keep
    data class Example(@Json(name = "key") val key1: String)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val jsonString = """
            {
                "key": "value"
            }
        """.trimIndent()

        val moshi = Moshi.Builder().add(KotlinJsonAdapterFactory()).build()
        val responseAdapter = moshi.adapter(Example::class.java)
        val actual = responseAdapter.fromJson(jsonString)

        require(actual!!.key1 == "value")
    }
}

build.gradle:
implementation "com.squareup.moshi:moshi-kotlin:1.14.0"
kapt "com.squareup.moshi:moshi-kotlin-codegen:1.14.0"
```
When run the snippet code using kotlin 1.7.20 and 1.8.0 give us different result. Important note this issue only happening when R8 enabled.

We found that using @field:Json or @JsonClass(generateAdapter = true) fix the issue. But we need make a lot of changes on our code base.

**Comment by NapasPayu** [comment]
Disabling [R8 full mode](https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md) works for me.
```
// gradle.properties
android.enableR8.fullMode=false
```

**Comment by ZacSweers** [comment]
> Disabling [R8 full mode](https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md) works for me.
> 
> ```
> // gradle.properties
> android.enableR8.fullMode=false
> ```

That's like saying shutting off the water fixes your leaky pipe :). You need to add the correct R8 rules to protect your reflectively serialized classes.

> We found that using `@field:Json` or @JsonClass(generateAdapter = true) fix the issue. But we need make a lot of changes on our code base.

Code gen will avoid this because it generate any R8 rules needed and mostly skips reflection. Field may work by coincidence, I'm not sure exactly what R8 is doing. It's also strange to use both `KotlinJsonAdapterFactory` (reflection) and code gen at the same time, you should just pick one.

Closing this because this is a proguard configuration issue on the user-side
