### ISSUE TITLE
UTF-8 Byte-order Mark causes parsing failure

### ISSUE THREAD

**Issue by toadzky** [square/moshi#169]
When an otherwise valid JSON response from an API includes the optional BOM (U+FEFF BYTE ORDER MARK), it fails to parse the stream because it doesn't know what to do with it. Can you start consuming it correctly?

My situation is a .NET Web API backend that is including the BOM and I can't make it stop.

**Comment by toadzky** [comment]
Nevermind, looks like it was fixed in 1.2.0, last retrofit release uses 1.1.0

**Comment by toadzky** [comment]
i do wonder why the test making sure it works correctly is ignored.

**Comment by toadzky** [comment]
also, i'm apparently too tired to be doing this at the moment, because the test fails when i thought it was passing.

**Comment by swankjesse** [comment]
This is what the spec says;

Implementations MUST NOT add a byte order mark to the beginning of a JSON text. In the interests of interoperability, implementations that parse JSON texts MAY ignore the presence of a byte order mark rather than treating it as an error.

https://tools.ietf.org/html/rfc7159

**Comment by swankjesse** [comment]
I'm tempted to recommend manually skipping the BOM before calling into Moshi. That makes your calling code worse, but it doesn't pollute other Moshi users with the BOM support. 

With rangeMatches it's a pretty short code snippet to detect and skip the BOM.

**Comment by JakeWharton** [comment]
It hasn't been implemented in Okio's public API yet.

**Comment by JakeWharton** [comment]
We are going to solve this at the Retrofit level. Moshi doesn't have any APIs which operate truly at the document level. Moshi's `JsonReader` can be used recursively such that a "root" object is actually just an object nested inside another `JsonReader`. Because of this, it doesn't make sense to put BOM skipping in the library. Also there are assumptions about only handling The One True Charset™ (aka UTF-8) whereas the BOM might disagree and Moshi isn't the right place for handling that.
