### ISSUE TITLE
Support Kotlin 1.9.0+

### ISSUE THREAD

**Issue by colintheshots-meetup** [square/moshi#1738]
I noticed that code has been landed to support Kotlin 1.9.0 by @ZacSweers but no release has been made to include it. I've been checking this repository's CHANGELOG daily for a new release. It's starting to become a problem, since we need to upgrade Kotlin for other dependencies.

Could we please release with the Kotlin 1.9 fixes in place?

**Comment by charlieneedham** [comment]
Is this likely to be supported soon? We have the same issue, needing to update Kotlin for other dependencies.

**Comment by ZacSweers** [comment]
Moshi 1.15.0 supports kotlin 1.9.0 and is documented as such in the changelog. What am I missing? 

https://github.com/square/moshi/blob/master/CHANGELOG.md

**Comment by colintheshots-meetup** [comment]
As far as I can tell, the Kotlin 1.9.x changes you wrote never made it to a release. Moshi 1.15.0 predates those fixes. And the CHANGELOG shows Kotlin 1.8.21 support. We ended up converting all of our remaining Moshi code to KotlinX-serialization, since I was unable to upgrade Kotlin when using Moshi 1.15.0.

**Comment by colintheshots-meetup** [comment]
I believe the issue here is that we Moshi-sealed was causing the errors. There's newer version of Moshi-sealed in the MoshiX repo to support new Kotlin versions. I'll close this ticket for now. Please feel free to re-open it with an error message if this doesn't fix your issue.

**Comment by ZacSweers** [comment]
To add clarity

Moshi _kapt_ code gen 1.15.0 supports kotlin 1.9.0. It's not _built_ against Kotlin 1.9.0. That's ok, what matters is what version the kotlinx-metadata-jvm library under the hood supports, which includes support for 1.9.0 in the version that Moshi 1.15.0 is built against. It is not built from the `master` branch because the master branch is a preparation for an eventual Moshi 2.0, so we cut 1.x releases from other branches to minimize changes.

For _everything else_ – Kotlin 1.9.0 is fully supported. Starting with Moshi 1.15.0, kapt support is actually straight up deprecated and won't support Kotlin 2.0 anymore. Please use KSP or (if you're ok with a compiler plugin) [moshi-ir](https://github.com/ZacSweers/MoshiX/tree/main/moshi-ir). Importantly, update your dependencies periodically :).
