### ISSUE TITLE
Update Okio to 3.4.0 or higher

### ISSUE THREAD

**Issue by nicbell** [square/moshi#1793]
It would be good for Okio to be updated as the version in this project has reported vulnerabilities.

#### How to fix?
Upgrade `com.squareup.okio:okio` to version `3.4.0` or higher.

https://security.snyk.io/vuln/SNYK-JAVA-COMSQUAREUPOKIO-5773320

**Comment by nicbell** [comment]
Ah it looks like it's already updated to in the TOML `okio = "com.squareup.okio:okio:3.7.0"` just hasn't been a release of Moshi in a while.

**Comment by JakeWharton** [comment]
It's also worth noting that Moshi does not exercise the codepath in question (which is not even really a vulnerability, just a bug that causes a crash).

Perhaps we can put out a point release. There only seems to be one or two bugfixes since the last release. Other than that it's just dependency bumps like this.

**Comment by JakeWharton** [comment]
1.15.1 released

**Comment by nicbell** [comment]
Thanks!
