### ISSUE TITLE
Proposal: Expose Moshi.Builder Factory List

### ISSUE THREAD

**Issue by naturalwarren** [square/moshi#414]
When calling `Moshi.newBuilder()` I'd like the ability to remove adapters and factories that were previously registered. Sometimes I want to deserializes classes differently depending on the context in which Moshi is used.

Would you be open to a PR that exposes the list?

**Comment by NightlyNexus** [comment]
I guess so.
My general pattern is to have a base Moshi instance that then feeds to branching scopes that add on to newBuilder instances.
I don't see the use case clearly here, but I also don't think this adds much API complexity. So, sgtm.

**Comment by naturalwarren** [comment]
I usually configure my Moshi instance with defaults and then tweak the instance based on the needs of a particular scope. Sounds like opening a PR is okay so I'll do so. Thanks Eric.

**Comment by swankjesse** [comment]
I don’t think we want this. Instead you should create a `NaturalWarrenMoshiBuilder` that wraps the `Moshi.Builder` and installs which adapters you want based on your needs.

Otherwise we need a strong sense of equality for adapters registered programmatically. We don’t have that. And so removing from the list is going to be awkward because you won’t know what to remove.

**Comment by naturalwarren** [comment]
That works - thanks Jesse!
