### ISSUE TITLE
Feature Request: include enclosing type name when parameterized platform time is missing adapter 

### ISSUE THREAD

**Issue by digitalbuddha** [square/moshi#557]
I received the following error message when converting a deeply nested pojo into json :

```
java.lang.IllegalArgumentException: Platform java.util.ArrayList<java.lang.String> annotated [] requires explicit JsonAdapter to be registered
```

It would be beneficial for the message to enclude the enclosing type's name to make it easier to know what field is the culprit

**Comment by NightlyNexus** [comment]
I'm unsure what you mean by enclosing type here, so correct me if I'm wrong below.

If I understand correctly, you'd like
```java
class Foo {
  ArrayList<String> list;
}
```
to fail creating an adapter with a message like: `Failed to create an adapter for field 'list' in Foo. Platform java.util.ArrayList<java.lang.String> annotated [] requires explicit JsonAdapter to be registered.` (Or maybe the original message is added as the cause to a new IllegalArgumentException, rather than appended to the new message.)

**Comment by digitalbuddha** [comment]
Yup you got it! Would be nice to have both the field name as well as the class it is in.
