### ISSUE TITLE
@Json annotation without @Target gets lost when using reflection on javaField of data class declaredMemberProperties

### ISSUE THREAD

**Issue by lfscheidegger** [square/moshi#585]
I have a kotlin project where I'm pulling out Gson for data class serialization and replacing it with Moshi. In the old version, I used Gson's `@Expose` (along with `@SerializedName`) to ensure that only a whitelisted set of declared data class properties ended up serialized. In addition, I have a test that iterates over all model classes using reflection to assert that all but a set of predefined declared properties in are in fact annotated with `@Expose`. The test looks roughly like this:

```
    model
        .declaredMemberProperties
        .filter { it.javaField?.isAnnotationPresent(Expose::class.java) == false }
        .forEach {
          check(it.name in WHITELISTED_PROPERTIES) { "Found disallowed non-exposed property ${it.name}" }
        }
```

After changing to Moshi, I replaced my usages of `@Expose` and `@SerializedName` simply by `@Json`, so I refactored this test to look like so:

```
    model
        .declaredMemberProperties
        .filter { it.javaField?.isAnnotationPresent(Json::class.java) == false }
        .forEach {
          check(it.name in WHITELISTED_PROPERTIES) { "Found disallowed non-exposed property ${it.name}" }
        }
```

The test then started failing, because `javaField?.isAnnotationPresent(Json::class.java)` returns false for all properties. I looked into any difference between `@Json` and `@Expose`, and the only thing I could find was that `@Expose` declares its `@Target` (specifically to `ElementType.FIELD`), while `@Json` has no declared `@Target`.

That got me suspicious so I changed my models to have their properties annotated explicitly with `@field:Json`, and sure enough, that got my test to pass again.

Then I looked at the commit history for `@Json` and noticed that it originally included `@Target` (set to `ElementType.METHOD` and `ElementType.FIELD`), but it was removed [here](https://github.com/square/moshi/commit/81bbe870f1e44cd829158ec96d44b413a85bf2c1). I couldn't find any discussion for why that was done, and other than a comment on the javadoc, I couldn't find a reason.

Is there a specific reason why target was removed from the annotation? It's not directly blocking anything I'm trying to do, but it'd sure be nice to not have to `@field:Json` every time instead of `@Json`. Any clarification would be super welcome, thanks!

**Comment by hzsweers** [comment]
Your issue is a kotlin language thing, not the target :).

I can't speak to why the target was removed in that PR (but can guess it's because kotlin's property surface area is slightly different semantically than Java and definitely different in how annotations are managed in bytecode, easiest to relax the rules).

I would suggest updating your test to read property annotations rather than fields if you want to avoid needing to put the field site target in the annotation. 

Alternatively, for each field you could look up the generated bean-style getter/setter methods and verify the annotation is there (because that's where the kotlin compiler will propagate them too). Note that this option might not be 100% reliable though, as there are conditions where the compiler will synthesize a placeholder "yourfield$annotations()" method for the sole purpose of bolting on the annotations there for later reference. Iirc that happens for private properties where no getter/setter methods are generated. This weird synthetic method is why we require JsonQualifier annotations to support FIELD target in Moshi's kotlin code gen, so we can set that site target in our copy and avoid the compiler generating the holder methods unnecessarily.

**Comment by swankjesse** [comment]
@hzsweers great explanation!

@lfscheidegger if you want to do reflection on Kotlin source code, you should use _Kotlin-reflection_ (ie. `kotlin-reflect`) and not Java reflection. Otherwise you’re making assumptions about how Kotlin source code maps to Java byte code, and those assumptions are easily violated.

**Comment by swankjesse** [comment]
No action for us to take on this.

**Comment by lfscheidegger** [comment]
Hey everyone, thanks for the quick replies!

@swankjesse I definitely agree that using java reflection on kotlin isn't great - I wrote this test a while back so I'm not 100% sure, but iirc I tried using only kotlin reflection first and it didn't work, and this was the only combination I'd managed to get something resembling my desired behavior.

I also just wrote a quick test to explore what I can do using only `kotlin-reflect`, and it seems that just reading the property annotations like @hzsweers suggested doesn't capture annotations that aren't explicitly targeted to property (either via `@Target(AnnotationTarget.PROPERTY)` or `@property:`):

```kotlin
@Retention(AnnotationRetention.RUNTIME)
annotation class ReflectionTest

@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.PROPERTY)
annotation class WithTargetReflectionTest

fun main(arg: Array<String>) {
  WithoutAnnotation::class.declaredMemberProperties.forEach { it -> println("${it.name}, ${it.annotations}") }
  UnqualifiedAnnotation::class.declaredMemberProperties.forEach { it -> println("${it.name}, ${it.annotations}") }
  QualifiedAnnotation::class.declaredMemberProperties.forEach { it -> println("${it.name}, ${it.annotations}") }
  
  PropertyQualifiedAnnotation::class.declaredMemberProperties.forEach { it -> println("${it.name}, ${it.annotations}") }
  UnqualifiedWithTarget::class.declaredMemberProperties.forEach { it -> println("${it.name}, ${it.annotations}") }
}

private data class WithoutAnnotation(val foo: String)
private data class UnqualifiedAnnotation(@ReflectionTest val foo: String)
private data class QualifiedAnnotation(@field:ReflectionTest val foo: String)

private data class PropertyQualifiedAnnotation(@property:ReflectionTest val foo: String)
private data class UnqualifiedWithTarget(@WithTargetReflectionTest val foo: String)
```

outputs:

```
foo, []
foo, []
foo, []
foo, [@com.ontrim.be.tools.ReflectionTest()]
foo, [@com.ontrim.be.tools.WithTargetReflectionTest()]
```

I'll go ahead and update my test to use the formulation above, and update my callsites to target `@property:Json` rather than `@field:Json`, which should solve the java-vs-kotlin reflection issues. Agree that there's nothing actionable here, just wanted to close the loop on some more experiments and how I don't think there's a way to get the annotation using `kotlin-reflect` if it doesn't include any targeting. Just for kicks I also tried pulling it out of the property's getter, which also (expectedly) didn't work.

Thanks again!
