### ISSUE TITLE
[Proposal] Kotlin Codegen to generate an AdapterFactory for all generated adapters

### ISSUE THREAD

**Issue by serj-lotutovici** [square/moshi#639]
At the moment all ProGuard users that want to leverage from `moshi:kotlin-codegen` are required to keep the names of all classes annotated with `@JsonClass`. Although the cost of the reflective lookup for each adapter is negligible, some projects may have a requirement to obfuscate the names of their models. 
Projects like [auto-value-moshi](https://github.com/rharter/auto-value-moshi/) and [auto-value-gson](https://github.com/rharter/auto-value-gson/) provide this functionality.
One could write a separate annotation processor that would do just that and port the naming logic from moshi, but in my opinion having this in the main source of truth would be a better option.

**Comment by hzsweers** [comment]
I think it's something that a separate library should do rather than Moshi directly. It's something that can get quite gnarly to scale in multimodule projects. It can also be a bit aggressive on classloading if you have a lot of models and it gets hit on startup, plus the worst case perf implication if you've got a massive when/if-else fall through to check Class equalities.

**Comment by hzsweers** [comment]
When I initially wrote the companion object extensions, it was with supporting this in a separate library like this in mind. Some related bits: https://github.com/square/moshi/pull/611

**Comment by swankjesse** [comment]
If you want, you could register the generated adapters manually. That’ll work and it shouldn't be much code.

If you wanna be extra fancy you could generate code to register ’em and call _that_ manually.

**Comment by serj-lotutovici** [comment]
Generating an extension function that registers all generated adapters sound like the best approach.
Thanks, Jesse & Zac.
