### ISSUE TITLE
NPE on RFC3339DateJsonAdapter when Date is null

### ISSUE THREAD

**Issue by markrebhan** [square/moshi#723]
Discovered this bug while attempting to serialize some JSON with a nullable `Date` field. 

Steps to NPE:

1. Send a `null` value into `RFC3339DateJsonAdapter.toJson()`
1. The adapter then sends that `null` value into `ISO8601Utils` to be formatted
1. The first thing the `format()` method does is creates a `Calendar` and sets the time with a date
1. Calling `Calendar.setTime(Date)` assumes the date is not null because the first thing it calls is `date.getTime()` which in this case, throws a NPE

**Comment by NightlyNexus** [comment]
Call `.nullSafe()` on the adapter.

**Comment by swankjesse** [comment]
Any action to take here? Should we document this?

**Comment by erikhuizinga** [comment]
I would have been helped a lot if this were documented with a short example. I will make a PR for the readme to clarify this feature.

For me as a newcomer to Moshi it took me a while to find this issue, but even the comment mentioning `.nullSafe()` -- which is the solution -- didn't help me, because I simply didn't understand when or where to use it.

I think with null safety being such a paramount feature of the Kotlin language, you should feature how to work with it in the readme.

**Comment by chrisjenx** [comment]
Not sure you want to reopen this, but moshi codegen doesn't handle this correctly it will generate:
```
0 -> timestamp = nullableDateAdapter.fromJson(reader)
```

When it should generate:
```
0 -> timestamp = nullableDateAdapter.nullSafe().fromJson(reader)
```

Is there something I'm missing?

**Comment by swankjesse** [comment]
Can fix.

**Comment by benjamin-bader** [comment]
It looks like it's an explicit choice to leave null-checking to installed or generated adapters.  Maybe the fix here should go in the `RFC3339DateJsonAdapter` adapter itself, rather than in generated code?

**Comment by ZacSweers** [comment]
Seems reasonable. @swankjesse?

**Comment by ZacSweers** [comment]
Opened a PR for this in #910
