### ISSUE TITLE
JsonDataException doesn't inherit from IOException

### ISSUE THREAD

**Issue by sosite** [square/moshi#829]
There are inconsistent because eg. `JsonUtf8Reader.beginObject()` tells us that it can throw an `IOException`. Unfortunately at the end of this function you `throw new JsonDataException()` which extends from `RuntimeException`. Why it's that?

**Comment by JakeWharton** [comment]
Because it's not an error with the transport of the data (i.e., IO), it's a
mismatch between your expected JSON shape as defined by the object and the
actual JSON shape as defined by the incoming data. IOExceptions are
perfectly normal things that you should handle and expect. JSON data
mismatches indicate programming bugs.

**Comment by matejdro** [comment]
Shouldn't that also apply to `JsonEncodingException`?
