### ISSUE TITLE
Kotlin inheritance with non-settable properties

### ISSUE THREAD

**Issue by 3mph4515** [square/moshi#835]
If I have an open class and inherited data class from it, Kotlin-moshi codegen skip default values. Is this intended behaviour or bug?
  
```kotlin
@JsonClass(generateAdapter = true)
data class B constructor(val test: String) : A(foo = "foo")
open class A constructor(val foo: String)
val b = B("test")
val json = jsonAdapter.toJson(b)
```
produces only
{"test":"test"} , w/out foo default value.

**Comment by ZacSweers** [comment]
This is happening because we only handle supertype properties if they're mutable. The logic to fix this would be to include "not settable" properties and filter those out during fromJson. 

I can see why it'd be expected to appear in toJson, but at the same time worry about the possible asymmetry of fromJson ignoring them and toJson not ignoring them.

@swankjesse @JakeWharton @rharter penny for your thoughts?

**Comment by ZacSweers** [comment]
FWIW - `KotlinJsonAdapterFactory` has the same behavior

**Comment by swankjesse** [comment]
Our rules are pretty simple: Moshi wants to both read and write JSON properties. If you have a property whose API permits writes but not reads, that’s a problem because it prevents you from testing your JSON.
