### ISSUE TITLE
Annotation for Ignoring Field when serializing only or deserializing only

### ISSUE THREAD

**Issue by cren90** [square/moshi#862]
The API I am interfacing with utilizes PATCH endpoints requiring request objects that are subsets of the object returned in the corresponding GET endpoint. To this end, it would be nice to be able to annotate fields as serialize only/deserialize only and have the moshi-kotlin-codegen generate the appropriate adapters.

**Comment by ZacSweers** [comment]
Could a proguard/R8 rule do this for you if we copied the annotations over to the generated type? Something like this:

```proguard
-if @your.custom.annotation.SerializeOnly class *
-assumenosideeffects class <1>JsonAdapter {
 public JsonAdapter fromJson(...);
}
```

**Comment by ZacSweers** [comment]
ah wait I just saw you want this on a per-property basis. So the solution depends on what your goal is.

### If the goal is functionality only

You can use the `SerializeOnly`/`DeserializeOnly` annotations in [moshi-lazy-adapters](https://github.com/serj-lotutovici/moshi-lazy-adapters). They're JsonQualifiers with factories you can wire into Moshi, so it works out of the box with kotlin code gen.

### If the goal is to reduce generated code...

I think that'd be hard to find a good API for, and you'd be better off writing two separate objects. Possibly make it a sealed class?

So instead of this

```kotlin
@JsonClass(generateAdapter = true)
data class PatchType(
  @SerializeOnly val serializeOnly: String,
  @DeserializeOnly val deserializeOnly: String
)
```

you could do something like this

```kotlin
sealed class PatchType(
    open val serializeOnly: String,
    open val deserializeOnly: String
) {

  @CustomSerializeOnly
  @JsonClass(generateAdapter = true)
  data class Upload(override val serializeOnly: String) : PatchType(serializeOnly, "...")

  @CustomDeserializeOnly
  @JsonClass(generateAdapter = true)
  data class Download(override val deserializeOnly: String) : PatchType("...", deserializeOnly)
}
```

And use the proguard trick above + the `PolymorhpicJsonAdapter`. It's not as simple as the original case, but it would at least get you adapters only targeting those types and also allow for the proguard trick to further optimize. Note the proguard trick only works if you want a type to be 100% read xor write, and doesn't help with per-field granularity. This approach does support the per-field granularity separately though

**Comment by ZacSweers** [comment]
Closing this as a feature request for now, but happy to continue the discussion if needed
