### ISSUE TITLE
Expected a double but was 811,91

### ISSUE THREAD

**Issue by dragossusi** [square/moshi#890]
I am trying to convert "811,91" to a float value but i get this error:

com.squareup.moshi.JsonDataException: Expected a double but was 811,91 at path $.data.result[15].amount

The json looks like this:
 "amount": "811,91"

**Comment by ZacSweers** [comment]
Because that is not a valid double/float that Java's double can format. You can write your own qualifier + adapter to parse the string and convert to a float manually with the formatting, or talk to your server developers and ask them to not send formatted strings if they're supposed to be read as float types
