### ISSUE TITLE
PolymorphicJsonAdapter +kotlin object + kotlin-reflect serialization don't work

### ISSUE THREAD

**Issue by Dkhusainov** [square/moshi#959]
Currently(moshi 1.8) this doesn't work. 

I you try to serialize kotlin `object` registerted in `PolymorphicJsonAdapter`(just to get one single entry with object type in JSON), you get an expected error "Cannot serialize object declaration".

This works with normal java reflection serialization.

**Comment by ZacSweers** [comment]
Kotlin object types are not supported at the moment. There is an [open PR](https://github.com/square/moshi/pull/934 ) with a proposal for this if you’re interested. Reflective Java serialization of kotlin types in general will be prohibited in the next release.

**Comment by Dkhusainov** [comment]
So the next release will be backwards incompatable regarding reflection serialization?

**Comment by ZacSweers** [comment]
Java reflection serialization of Kotlin object types was never officially supported. The next release just codifies that. If it worked before, it was by coincidence.

**Comment by ZacSweers** [comment]
Sorry but that won’t be happening. Intentionally supporting undefined behavior is not a goal of Moshi, nor should it be an intentional design of kotlin consumers of it. Yes, this will reveal some cases like this to users that didn’t realize it before. That’s why we’re enforcing this with an up-front error message, rather than punt it to an esoteric NPE or missing qualifier resulting in wrong runtime behavior.
